//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user92_dbEntities : DbContext
    {
        public user92_dbEntities()
            : base("name=user92_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RentCar_AgreementStatus> RentCar_AgreementStatus { get; set; }
        public virtual DbSet<RentCar_Car> RentCar_Car { get; set; }
        public virtual DbSet<RentCar_CarClasses> RentCar_CarClasses { get; set; }
        public virtual DbSet<RentCar_CarColors> RentCar_CarColors { get; set; }
        public virtual DbSet<RentCar_Client> RentCar_Client { get; set; }
        public virtual DbSet<RentCar_Employee> RentCar_Employee { get; set; }
        public virtual DbSet<RentCar_EmployeeRole> RentCar_EmployeeRole { get; set; }
        public virtual DbSet<RentCar_EmployeeStatus> RentCar_EmployeeStatus { get; set; }
        public virtual DbSet<RentCar_RentalAgreement> RentCar_RentalAgreement { get; set; }
        public virtual DbSet<RentCar_TransmissionType> RentCar_TransmissionType { get; set; }
    }
}
