//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentCar_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentCar_Client()
        {
            this.RentCar_RentalAgreement = new HashSet<RentCar_RentalAgreement>();
        }
    
        public int ClientId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Fathername { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PasportSeries { get; set; }
        public string PasportNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string DriversLicenseSeries { get; set; }
        public string DriversLicenseNumber { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<bool> Complaints { get; set; }
        public Nullable<bool> BlackList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentCar_RentalAgreement> RentCar_RentalAgreement { get; set; }
    }
}
