//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentCar_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentCar_Employee()
        {
            this.RentCar_RentalAgreement = new HashSet<RentCar_RentalAgreement>();
        }
    
        public int EmployeeId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Fathername { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public int Status { get; set; }
        public string PhotoPath { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual RentCar_EmployeeRole RentCar_EmployeeRole { get; set; }
        public virtual RentCar_EmployeeStatus RentCar_EmployeeStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentCar_RentalAgreement> RentCar_RentalAgreement { get; set; }
    }
}
