//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentCar_RentalAgreement
    {
        public int RentalAgreementId { get; set; }
        public int ClientId { get; set; }
        public int CarId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime AgreementStartDate { get; set; }
        public System.DateTime AgreementFinishDate { get; set; }
        public int Status { get; set; }
    
        public virtual RentCar_AgreementStatus RentCar_AgreementStatus { get; set; }
        public virtual RentCar_Car RentCar_Car { get; set; }
        public virtual RentCar_Client RentCar_Client { get; set; }
        public virtual RentCar_Employee RentCar_Employee { get; set; }
    }
}
