//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentCar_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentCar_Car()
        {
            this.RentCar_RentalAgreement = new HashSet<RentCar_RentalAgreement>();
        }
    
        public int CarId { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public int YearOfRelease { get; set; }
        public string Color { get; set; }
        public string PhotoPath { get; set; }
        public int CarClass { get; set; }
        public int RentCost { get; set; }
        public int TransmissionType { get; set; }
        public double EngineSize { get; set; }
        public int CarPower { get; set; }
        public bool Remove { get; set; }
        public string CarNumber { get; set; }
        public int CarRegion { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual RentCar_CarClasses RentCar_CarClasses { get; set; }
        public virtual RentCar_CarColors RentCar_CarColors { get; set; }
        public virtual RentCar_TransmissionType RentCar_TransmissionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentCar_RentalAgreement> RentCar_RentalAgreement { get; set; }
    }
}
